version: '3.4'
services:
  churn:
    image: backchurn:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    entrypoint: [
      "uvicorn", "app.main:app", "--reload", "--port" ,"5000", "--host", "0.0.0.0"
    ]
